# Generated by Django 4.2.4 on 2023-08-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bookappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='payment',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.service'),
            preserve_default=False,
        ),
    ]
