# Generated by Django 4.2.4 on 2023-08-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bookappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
