# Generated by Django 4.2.4 on 2023-09-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_bookappointment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='service',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
