# Generated by Django 4.2.4 on 2023-09-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_bookappointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bookappointment')),
            ],
        ),
    ]
