# Generated by Django 4.2.4 on 2023-09-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_booked',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
