# Generated by Django 4.2.4 on 2023-09-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_timeslot_date_remove_timeslot_is_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
